# MediaWEB appveyor configuration for Windows and Linux (x64)

# Common configuration
image: 
- Visual Studio 2017
- Ubuntu

platform: x64

version: 1.0.0.{build}

stack: go 1.10

install:
  # Windows
  - cmd: set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - cmd: go get github.com\mattn\goveralls
  - cmd: '%GOPATH%\src\github.com\midstar\mediaweb\scripts\install_deps.bat'

  # Linux
  - sh: export GOPATH=/usr/go
  - sh: export PATH=$GOPATH/bin:$PATH
  - sh: sudo chmod -R a+rwx $GOPATH
  - sh: sh $GOPATH/src/github.com/midstar/mediaweb/scripts/install_deps.sh
 
build_script:
  # Common
  - go test -v -cover github.com/midstar/mediaweb -coverprofile=coverage.out

  # Windows
  - cmd: '%GOPATH%/bin/goveralls -coverprofile=coverage.out -service=appveyor-ci -repotoken=%COVERALLS_TOKEN%'
  - cmd: '%GOPATH%\src\github.com\midstar\mediaweb\scripts\build.bat %APPVEYOR_BUILD_VERSION%'
  - cmd: 7z a mediaweb_windows_x64.zip mediaweb.conf %GOPATH%\bin\mediaweb.exe 

  # Linux (don't publish to coveralls.io)
  - sh: 'sh $GOPATH/src/github.com/midstar/mediaweb/scripts/build.sh $APPVEYOR_BUILD_VERSION'
  - sh: tar -zcvf mediaweb_linux_x64.tar.gz mediaweb.conf -C $GOPATH/bin/ mediaweb

  # Deploy to GitHub (only on master AND on tags)
  deploy:
    release: mediaweb-v$(appveyor_build_version)
    description: ''
    provider: GitHub
    auth_token:
      secure: $(GITHUB_TOKEN) # your encrypted token from GitHub
    draft: false
    prerelease: false
    on:
      branch: master                 # release from master branch only
      APPVEYOR_REPO_TAG: true        # deploy on tag push only

for:
  
# Special configurations for Windows
-
  matrix:
    only:
      - image: Visual Studio 2017

  clone_folder: c:\gopath\src\github.com\midstar\mediaweb

  environment:
    GOPATH: c:\gopath

  artifacts:
    - path: mediaweb_windows_x64.zip
      name: mediaweb_windows_x64.zip

# Special configurations for Linux
-
  matrix:
    only:
      - image: Ubuntu

  clone_folder: /usr/go/src/github.com/midstar/mediaweb

  environment:
    GOPATH: /usr/go

  artifacts:
    - path: mediaweb_linux_x64.tar.gz
      name: mediaweb_linux_x64.tar.gz

