# MediaWEB appveyor configuration for Windows and Linux (x64)

# Common configuration
image: 
- Visual Studio 2017
- Ubuntu

platform: x64

environment:
  - clone_folder: c:\gopath\src\github.com\$username\$project
  - GOPATH: c:\gopath

install:
  # Windows
  - cmd: set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - cmd: go get github.com\mattn\goveralls
  - cmd: '%GOPATH%\src\github.com\midstar\mediaweb\scripts\install_deps.bat'

  # Linux
  - sh: export GOPATH=/usr/go/
  - sh: export PATH=$GOPATH/bin:$PATH
  - sh: '$GOPATH/src/github.com/midstar/mediaweb/scripts/install_deps.sh'
 
build_script:
  # Common
  - go test -v -cover github.com/midstar/mediaweb -coverprofile=coverage.out

  # Windows
  - cmd: '%GOPATH%/bin/goveralls -coverprofile=coverage.out -service=appveyor-ci -repotoken=%COVERALLS_TOKEN%'
  - cmd: '%GOPATH%\src\github.com\midstar\mediaweb\scripts\build.bat %APPVEYOR_BUILD_VERSION%'

  # Linux (don't publish to coveralls.io)
  #- sh: '$GOPATH/src/github.com/midstar/mediaweb/scripts/build.sh $APPVEYOR_BUILD_VERSION'


# here we are going to override common configuration
for:

# Master branch
-
  branches:
    only:
     - master

  version: 1.0.0.{build}