# Common configuration

platform: x64

clone_folder: c:\gopath\src\github.com\midstar\mediaweb

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get github.com\mattn\goveralls
  - '%GOPATH%\src\github.com\midstar\mediaweb\scripts\install_deps.bat'
 
build_script:
  - go test -v -cover github.com\midstar\mediaweb -coverprofile=coverage.out
  - '%GOPATH%/bin/goveralls -coverprofile=coverage.out -service=appveyor-ci -repotoken=%COVERALLS_TOKEN%'
  - '%GOPATH%\src\github.com\midstar\mediaweb\scripts\build.bat %APPVEYOR_BUILD_VERSION%'


# here we are going to override common configuration
for:

# Master branch
-
  branches:
    only:
     - master

  version: 1.0.0.{build}