# MediaWEB appveyor configuration for Windows (x64) and Linux (x64 + ARM)

# Common configuration
image: 
- Visual Studio 2017
- Ubuntu

platform: x64

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

version: 1.0.0.{build}

stack: go 1.11

install:
  # Windows
  - cmd: set PATH=%GOPATH%\bin;%PATH%
  - cmd: go get github.com\mattn\goveralls
  - cmd: '%GOPATH%\src\github.com\midstar\mediaweb\scripts\install_deps.bat'

  # Linux
  - sh: export GOPATH=/usr/go
  - sh: export PATH=$GOPATH/bin:$PATH
  - sh: sudo chmod -R a+rwx $GOPATH
  - sh: sh $GOPATH/src/github.com/midstar/mediaweb/scripts/install_deps.sh
 
build_script:
  # Common
  - go test -v -cover github.com/midstar/mediaweb -coverprofile=coverage.out

  # Windows and publish result on coveralls.io
  - cmd: '%GOPATH%/bin/goveralls -coverprofile=coverage.out -service=appveyor-ci -repotoken=%COVERALLS_TOKEN%'
  - cmd: '%GOPATH%\src\github.com\midstar\mediaweb\scripts\build.bat %APPVEYOR_BUILD_VERSION%'
  - sh: 'copy scripts\service.bat .'
  - sh: 'copy configs\mediaweb.conf .'
  - cmd: 7z a mediaweb_windows_x64.zip mediaweb.exe mediaweb.conf service.bat

  # Linux PC/x64
  - sh: 'sh $GOPATH/src/github.com/midstar/mediaweb/scripts/build.sh $APPVEYOR_BUILD_VERSION'
  - sh: 'cp scripts/service.sh .'
  - sh: 'cp configs/mediaweb.conf .'
  - sh: tar -zcvf mediaweb_linux_x64.tar.gz  mediaweb mediaweb.conf service.sh

  # Test service installation/uninstallation script
  - sh: 'sudo -E sh scripts/service_test.sh'

  # Linux ARM (cross compile from linux x64)
  - sh: rm mediaweb
  - sh: 'sh $GOPATH/src/github.com/midstar/mediaweb/scripts/build_cross_arm.sh $APPVEYOR_BUILD_VERSION'
  - sh: tar -zcvf mediaweb_linux_arm.tar.gz mediaweb mediaweb.conf service.sh

# Deploy to GitHub (only on master AND on tags)
deploy:
  release: mediaweb-v$(APPVEYOR_BUILD_VERSION)
  description: ''
  provider: GitHub
  auth_token:
    secure: C6VrW1yhX0pNCEarV0anjNU8gcM0tKbMGf+7yhuh8rLe+HnCzlzLu9Uq7EWMtYHG
  draft: false
  prerelease: false
  on:
    branch: master

for:
  
# Special configurations for Windows
-
  matrix:
    only:
      - image: Visual Studio 2017

  clone_folder: c:\gopath\src\github.com\midstar\mediaweb

  environment:
    GOPATH: c:\gopath

  artifacts:
    - path: mediaweb_windows_x64.zip
      name: mediaweb_windows_x64.zip

# Special configurations for Linux
-
  matrix:
    only:
      - image: Ubuntu

  clone_folder: /usr/go/src/github.com/midstar/mediaweb

  environment:
    GOPATH: /usr/go

  artifacts:
    - path: mediaweb_linux_x64.tar.gz
      name: mediaweb_linux_x64.tar.gz
    - path: mediaweb_linux_arm.tar.gz
      name: mediaweb_linux_arm.tar.gz

