#!/bin/sh
set -e

if [ "$1" = install ] || [ "$1" = upgrade ]; then
    echo "Checking MediaWEB dependencies"

    if ! [ -x "$(command -v systemctl)" ]; then
        echo "ERROR! systemctl is not installed."  1>&2
        echo "" 1>&2
        echo "To install MediaWEB the system needs to support systemd services." 1>&2
        echo "" 1>&2
        exit 1
    else
        echo "systemctl: ok"
    fi

    if ! [ -x "$(command -v ffmpeg)" ]; then
        echo "Warning! ffmpeg is not installed." 1>&2
        echo "" 1>&2
        echo "To generate video thumbnails ffmpeg needs to be installed." 1>&2
        echo "" 1>&2
    else
        echo "ffmpeg:    ok"
    fi

    systemctl is-active --quiet mediaweb && {
        echo "Stopping MediaWEB service"
        systemctl stop mediaweb || {
            echo "ERROR! Unable to stop MediaWEB service" 1>&2
            echo "" 1>&2
            exit 1
        }
    }

    systemctl is-enabled --quiet mediaweb 2> /dev/null && {  
        echo "Disabling MediaWEB service"   
        systemctl disable mediaweb || {
            echo "ERROR! Unable to disable MediaWEB service" 1>&2
            echo "" 1>&2
            exit 1
        }
    }

    exit 0
fi
